### ISSUE TITLE
"Cover" Exception, VS2015

### ISSUE THREAD

**Issue by JakenVeina** [axodox/AxoTools#127] opened 2017-10-14 02:04 UTC
I suddenly started receiving the following exception at work yesterday, using VS2015. It occurs in the VS "Output" window any time I try and run "Cover" on a test or set of tests. "Run" and "Debug" still seem to be working fine. I went ahead and upgraded to the latest release, and still receive the same error.

I imagine this is something specific to my setup at work, probably some Group Policy change that got pushed out overnight, as I haven't applied any updates or changes to AxoCover or Visual Studio, aside form upgrading AxoCover after this issue presented. I was just hoping you could give me some insight into what the underlying cause is, so I can try and work around it on my system, or get IT involved.

Thanks in advance.

```
Test execution started.
Test execution failed.
SerializableException: Could not create service.
  at AxoCover.Models.TestProcess`1..ctor(IProcessInfo processInfo, CommunicationProtocol protocol) in C:\projects\axotools\AxoCover\Models\TestProcess.cs:line 39
  at AxoCover.Models.ExecutionProcess.Create(String[] testPlatformAssemblies, IHostProcessInfo hostProcess, TestPlatform testPlatform, CommunicationProtocol protocol) in C:\projects\axotools\AxoCover\Models\ExecutionProcess.cs:line 28
  at AxoCover.Models.AxoTestRunner.RunTests(TestItem testItem, Boolean isCovering, Boolean isDebugging) in C:\projects\axotools\AxoCover\Models\AxoTestRunner.cs:line 89
  at AxoCover.Models.TestRunner.<>c__DisplayClass31_0.<RunTestsAsync>b__0() in C:\projects\axotools\AxoCover\Models\TestRunner.cs:line 53
```

**Comment by axodox** [comment] 2017-10-15 08:06
Code coverage uses OpenCover which registers itself as a profiler, normally this does not require admin rights, and should work for any user. You may check the Windows Event Log, maybe it contains more information about why OpenCover crashed or similar.

**Comment by axodox** [comment] 2017-10-15 10:00
Duplicate of https://github.com/axodox/AxoTools/issues/109 please refer to that in future.

**Closed by axodox** 2017-10-15 10:00 UTC
Labels: duplicate
