### ISSUE TITLE
Tests Run does nothing first time (but OK second time)

### ISSUE THREAD

**Issue by fgenolini** [axodox/AxoTools#34] opened 2017-04-10 11:47 UTC
After upgrading VisualStudio 2017 to the latest update (15.1 26403.0), AxoCover 1.0.71.1 (build version 1.0.22) always fails to run the tests when clicking on Tests > Run.  Click a second time and tests run.
Using VsTestRunner

**Comment by axodox** [comment] 2017-04-10 21:36
Unfortunately I am not able to reproduce this issue. Can you provide the contents of the output window when you select AxoCover?

**Comment by fgenolini** [comment] 2017-04-11 07:31
Seems to be fixed in today's Visual Studio update: build 26403.3.

Bug was 95% repeatable in 64-bit Windows 10, and I never saw it on 32-bit Windows 10.
Also only happened after I reached the 75 unit tests (C#), including a few more SpecFlow TDD acceptance tests.

**Comment by axodox** [comment] 2017-04-11 08:31
Based on your response, I would ask a few more questions:
- As I see you are running a different set of tests in the two examples you have provided. Can you provide a failed and a successful result for the same set of tests?
- Are you sure the test coverage zero (that is 0.0% on the AxoCover UI) in the first case? As the log shows small, but greater than zero coverage. (So we can rule out that AxoCover is processing the coverage results wrong.)
- Can you verify if the percentages in the output window are realistic or not? As if the running tests are correct, but the coverage measured by OpenCover are wrong, then problem might be in OpenCover.
- Can you confirm that the previous test run cannot affect the next one in some way (database usage, locked files, failed cleanup etc.)?

**Comment by fgenolini** [comment] 2017-04-11 08:52
I have found a fairly reliable way to make the first run fail: In the second tab (Green tick), select one test.
If you do this, then the output only lists that test as the Test being run, but the second time all the tests are run.  This might actually be a feature that is undesirable and astonishing, and not "Poka Yoke" proof.

What you see in the fault report is therefore my understanding of "same set of tests", but for the code it might not actually be the case: so you have found in me a user fool enough that does not understand how AxoCover works.

As a suggestion: could you reset any selection before the "Tests | Run" is executed so that the tests are run off the selection in the first pane (the "Tests | Run" tree), and ignore the selection from the second pane (the green tick list of all the test methods).

The selection in AxoCover is the least intuitive for me and it took me many days to understand why all my coverage was highlighted as blue (selected) instead of the intuitive green.  So now I click on any random test in the second pane (Green tick) before looking at code coverage, so that I can see the expected green colour.

I think that I started having these "failures on first click" since I started this practice, whereas before I never selected any test method from the second pane (Green tick).

So this might be user error from the very start, but this means that the principle of least astonishment as been broken by AxoCover, and very likely a mistake proofing code review would be appropriate at this time.

Thanks again for a fantastic tool, this has changed the way I code in so many ways.

**Comment by axodox** [comment] 2017-04-11 10:21
The results tabs (green, yellow, red) are cleared on test run, so first time, when you select a test there it runs the selected test, and in second run it is different, as on the main tab a different test is selected.

The colors can be changed in the settings. The blue color on default shows the coverage of the selected tests. **If you are not interested in coverage by test feature, you can disable it in settings, so you will not see the blue color.**

See here:
![image](https://cloud.githubusercontent.com/assets/22882208/24904612/4c03cdc0-1eb1-11e7-85e4-695df87f901b.png)

**Comment by axodox** [comment] 2017-04-11 10:21
I will change the color of selected to be a brighter green in next release.

**Comment by axodox** [comment] 2017-04-11 10:23
I also plan to write a tutorial at one point, but as I do not have much free time, it might take a while.

**Comment by fgenolini** [comment] 2017-04-11 12:28
Thanks, works as designed, user re-educated ;-)

**Comment by axodox** [comment] 2017-04-11 15:14
Great news, will close the issue then.

**Closed** 2017-04-11 15:15 UTC
Labels: bug
