### ISSUE TITLE
Cover test is stuck on "Initializing test runner..." if a C# "Shared Project" is in the solution 

### ISSUE THREAD

**Issue by Crewman123** [axodox/AxoTools#89] opened 2017-06-09 14:45 UTC
Hi there,
I am using the master-1.1.191 release.

I have a solution with a Shared Project. If I click "run tests" everything works fine.
However if I click on "Cover tests" the test runner is stuck on initialize, also the "Abort" will not abort the initializing Process of the runner.

**Comment by axodox** [comment] 2017-06-09 20:29
Thanks for reporting this, I will try to reproduce the issue.

**Comment by Crewman123** [comment] 2017-06-12 06:18
Here is a test project I used to reproduce this error.
http://www81.zippyshare.com/v/j337GAes/file.html

**Comment by Crewman123** [comment] 2017-06-14 09:21
Return from OpenCover.Console:
`Unable to process the filter '+[]*'. Please check your syntax against the usage guide and try again.
The usage guide can also be found at https://github.com/OpenCover/opencover/wiki/Usage.
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues`

Issue solved by unchecking "Include solution output only" default is checked and using default filter `+[*]*`
![issuesolved](https://user-images.githubusercontent.com/29308103/27125028-4456f0a6-50f3-11e7-929b-f0333acc4c23.PNG)

**Comment by axodox** [comment] 2017-06-14 13:20
I do not have much free time right now, but based on the description I would say this is a problem with the way projects are discovered in a solution. It is likely that shared projects use different API / properties, hence an empty assembly filter is added.

If you have more time than me, then you might want to check the public async Task<TestSolution> GetTestSolutionAsync(Solution solution, string testSettings) method in TestProvider.cs, where the test and code assemblies are discovered, I think this issue might originate there.

**Comment by axodox** [comment] 2017-07-07 23:07
I have tried your solution, but I am not able to reproduce the issue with [latest master build](https://github.com/axodox/AxoTools/releases/tag/master-1.1.222) and latest VS2017.

**Comment by axodox** [comment] 2017-07-24 09:13
Problem fixed in latest release.

**Closed by axodox** 2017-07-24 09:13 UTC
Labels: enhancement, prerelease-bug, waiting for info
