### ISSUE TITLE
Tests results are not shown

### ISSUE THREAD

**Issue by pfuhlert** [axodox/AxoTools#94] opened 2017-06-23 13:40 UTC
Hello,

first of all thanks for your work and effort! Your extension looks very useful! 

When I use your extension everything seems to run fine. I can choose the tests I want and run them. However, no results seem to be shown in the Report tab. It only says "run tests to get a coverage report". Which I just did before. The tests in the "Tests" tab also do not change color. They stay blue even after the tests ran.

In the console output I can see some metrics like "Visited Classes, Methods, Points and Branches". It also ends with "Coverage executor has finished.". Any ideas?

**Comment by axodox** [comment] 2017-07-02 10:58
Can you post the whole log, also a version number of AxoCover?

**Comment by pfuhlert** [comment] 2017-07-03 14:04
Can you tell me where I find the log? The Activitylog.xml only contains the initialization of the plugin.

**Comment by axodox** [comment] 2017-07-03 14:28
Sorry, vague wording, I just meant the console output.

**Comment by pfuhlert** [comment] 2017-07-04 09:20
Oh sorry from my side aswell. I could've guessed that. 

I use Visual Studio Pro 2017 v5.2 26430.12. I hope its ok that it is in German. I don't see anything suspicious. I also can view the *.tex file and it looks fine.

> Coverage executor has started.
> Executing: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
> Microsoft (R)-Testausfhrungs-Befehlszeilentool Version 15.0.26228.0
> Copyright (c) Microsoft Corporation.  Alle Rechte vorbehalten.
> 
> Testausfhrung wird gestartet, bitte warten...
> Erfolgreich   ConstructorDomainNull
> Erfolgreich   ConstructorDomainEmpty
> Erfolgreich   ConstructorUserNull
> Erfolgreich   ConstructorUserEmpty
> Erfolgreich   ConstructorPasswordNull
> Erfolgreich   ConstructorPasswordEmpty
> 
> Ergebnisdatei: [...]_DESKTOP 2017-07-04 10_01_32.trx
> 
> Gesamtanzahl von Tests: 19. Erfolgreich: 18. Fehlgeschlagen: 1. šbersprungen: 0.
> Testausfhrungszeit: 2,5457 Minuten
> Committing...
> 
> Visited Classes 55 of 527 (10.44)
> Visited Methods 250 of 3910 (6.39)
> Visited Points 1505 of 21577 (6.98)
> Visited Branches 435 of 9879 (4.40)
> 
> ==== Alternative Results (includes all methods including those without corresponding source) ====
> Alternative Visited Classes 58 of 588 (9.86)
> Alternative Visited Methods 262 of 4354 (6.02)
> Coverage executor has finished.

**Comment by axodox** [comment] 2017-07-04 10:13
In the test output directory there will be an xml file generated by OpenCover, it should have same name and location as trx, just xml extension. That where the test coverage is stored and the issue might be with its creation or importing. Unfortunately this is likely be sensitive information, as it contains the listing of you classes and methods. So if you can I suggest to create a small sample project which can be used to reproduce the issue and send it.

I would also take a look if exceptions appear in the AxoCover console output window.

My last suggestion is that soon there will be a new version released from AxoCover, which works differently, you may give it a try by changing to master branch in releases and updates:
![image](https://user-images.githubusercontent.com/22882208/27825829-258bfcb6-60b1-11e7-9604-3a319590f309.png)
See if that works with your project. Switching the versions don't take more than 10 seconds + restart VS, you can roll back the version if it does not work for you.

Also no problem with German, I speak German a little, so some chance to practice is always welcomed :)

**Comment by pfuhlert** [comment] 2017-07-05 07:59
Thanks for your reply. Under "Releases and Updates" I only have the first checkbox to install updates automatically, not the dropdown to switch branches. Any idea why? I have Axocover 1.0.73.8.

I created a new test project and could resolve my error by switching to MsTestRunner instead of using VsTestrunner in the Axocover settings. The problem still remains in my (fairly large) solution that I want to test. 

I found that the *.trx file gives me another error:

> Error	AxoTest	[...].AxoTest	Die [...].ClassInit-Methode weist die falsche Signatur auf. Parameter "1" muss vom Typ "Microsoft.VisualStudio.TestTools.UnitTesting.TestContext" sein.

Translation: 
> The ClassInit-Method has the wrong signature. Parameter 1 should be of type > Microsoft.VisualStudio.TestTools.UnitTesting.TestContext

The error seems wrong to me because in my test file I use:

>         [ClassInitialize()]
>        public static void ClassInit(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext context)
>       {
 >           // Method intentionally left empty. Some static stuff could be set here
 >      }

(I referenced the Testcontext with the namespace just for test purposes)

Removing this function and rebuilding my project did the trick. So there seems to be a bug here I guess..

**Comment by axodox** [comment] 2017-07-05 08:41
You may download the new version from here: https://github.com/axodox/AxoTools/releases/tag/master-1.1.211

The new version does not use trx files, so that should be no longer a problem.

**Comment by axodox** [comment] 2017-07-05 08:42
I think your firewall might interfere with the check for updates, but it is hard to tell, I will add some logging to the telemetry for this, maybe that will uncover the issue.

**Comment by axodox** [comment] 2017-07-08 07:29
I have updated the master to https://github.com/axodox/AxoTools/releases/tag/master-1.1.222, as the 211 build had some regressions.

**Comment by pfuhlert** [comment] 2017-07-14 14:13
Your new release seems to perform better. I will be able to test this on our "real" solution next week.

**Comment by axodox** [comment] 2017-07-14 15:49
OK. The fix has been released to markedplace since then with all the other new things and fixes from master.

**Closed** 2017-07-24 15:09 UTC
Labels: question, waiting for info

**Comment by cprouveu** [comment] 2017-10-16 12:58
Hello, 

I use visual studio 2017 and axo (1.1.4.4) don't detect the test 
"using Microsoft.VisualStudio.TestTools.UnitTesting"
but he accept their "using Nunit.Framework" 
I need the both.

How can I do ?

**Comment by axodox** [comment] 2017-10-16 13:07
You cannot use both at the same time, however you can switch between them quickly in the settings:
![image](https://user-images.githubusercontent.com/22882208/31613498-97166f14-b283-11e7-82d4-02495401abdb.png)

**Comment by cprouveu** [comment] 2017-10-16 13:12
Ok, thank you !
