### ISSUE TITLE
[DataRow] attribute is not supported

### ISSUE THREAD

**Issue by StefanMihaylov** [axodox/AxoTools#61] opened 2017-05-11 20:44 UTC
I found that the new [DataRow] attribute in MSTest v.2 (similar to NUnit [TestCase] attribute) is not supported. The following error message is returned:

 UTA007: Method '...' defined in class '....' does not have correct signature. Test method marked with the [TestMethod] attribute must be non-static, public, does not return a value and should not take any parameter. for example: public void Test.Class1.Test().

It would be nice if [DataRow] attribute is supported.

**Comment by axodox** [comment] 2017-05-21 07:23
I have added some improvements for MSTestV2 support, please try https://github.com/axodox/AxoTools/releases/tag/master-1.1.171 or later.

**Comment by StefanMihaylov** [comment] 2017-05-21 18:27
I have tested the 1.1.171 and now the DataRow attribute is supported. Great job! 
I also found a bug: when the unit tests were run through the AxoCover tool, they disappeared in the VS Test explorer. The VS has to be restarted in order to restore the build-in unit test recovering.

**Comment by axodox** [comment] 2017-05-21 20:59
That is likely to be a side effect, as the main problem was not the lack of DataRow support, but that AxoCover used a different version of the MsTestV2 adapter than what was used by the test project, this in turn referenced different versions of MsTestV2 framework.

The problem is that the public APIs of these files are being changed, so when loading an adapter with a different version of framework it will fail. I cannot use the official version of the test adapter, as I have some changes needed for AxoCover to work properly. The workaround I found is to back up the conflicting files in another directory, so then only the correct version of the DLL is available. - But Test Explorer depends on these files, so moving them breaks it.

I will try to find a better solution, but it seems to be hard to solve, as the test runners load DLLs into separate app domains, which they create while discovering and running the tests. This prevents using AssemblyResolve effectively. Setting assembly redirection will not work either as the versions of these DLLs are not updated between releases, so they are all the same.

**Comment by axodox** [comment] 2017-07-02 15:44
Hi again, it took some time but I managed to come up with another solution, which have been merged to master. This should keep VS discovery working, while the datarow discovery issue is still fixed.

**Comment by axodox** [comment] 2017-07-02 15:45
Available in https://github.com/axodox/AxoTools/releases/tag/master-1.1.210

**Closed by axodox** 2017-07-02 15:45 UTC
Labels: enhancement
